services:
  estate-service:
    container_name: estate-service
    image: estate-service
    build:
      context: estate-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_PORT: ${ESTATE_SERVICE_PORT}
      SPRING_DATABASE_URL: ${ESTATE_SERVICE_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${ESTATE_SERVICE_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ESTATE_SERVICE_DATABASE_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${ESTATE_SERVICE_KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${ESTATE_SERVICE_KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_NAME: ${KEYCLOAK_REALM_NAME}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      STATIC_SERVICE_URL: ${STATIC_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      EMAIL_SERVICE_URL: ${EMAIL_SERVICE_URL}
      REDIS_HOST: ${REDIS_HOST}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    env_file:
      - .env
    volumes:
      - ./estate-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.estate-service.rule=Host(`estate-service.domain.com`)"
      - "traefik.http.routers.estate-service.entrypoints=web"
    restart: on-failure
    network_mode: "host"

  static-service:
    container_name: static-service
    image: static-service
    build:
      context: static-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_PORT: ${STATIC_SERVICE_PORT}
      SPRING_DATABASE_URL: ${STATIC_SERVICE_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${STATIC_SERVICE_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${STATIC_SERVICE_DATABASE_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      KEYCLOAK_CLIENT_ID: ${STATIC_SERVICE_KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${STATIC_SERVICE_KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_NAME: ${KEYCLOAK_REALM_NAME}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    env_file:
      - .env
    volumes:
      - ./static-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
      - redis
    restart: on-failure
    network_mode: "host"

  user-service:
    container_name: user-service
    image: user-service
    build:
      context: user-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_PORT: ${USER_SERVICE_PORT}
      SPRING_DATABASE_URL: ${USER_SERVICE_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${USER_SERVICE_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${USER_SERVICE_DATABASE_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${USER_SERVICE_KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${USER_SERVICE_KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_NAME: ${KEYCLOAK_REALM_NAME}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
    env_file:
      - .env
    volumes:
      - ./user-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
    restart: on-failure
    network_mode: "host"

  email-service:
    container_name: email-service
    image: email-service
    build:
      context: email-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_PORT: ${EMAIL_SERVICE_PORT}
      SPRING_DATABASE_URL: ${EMAIL_SERVICE_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${EMAIL_SERVICE_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${EMAIL_SERVICE_DATABASE_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${EMAIL_SERVICE_KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${EMAIL_SERVICE_KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_NAME: ${KEYCLOAK_REALM_NAME}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
    env_file:
      - .env
    volumes:
      - ./email-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - mysql
      - keycloak
    restart: on-failure
    network_mode: "host"

  booking-service:
    container_name: booking-service
    image: booking-service
    build:
      context: booking-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_APPLICATION_PORT: ${BOOKING_SERVICE_PORT}
      SPRING_DATABASE_URL: ${BOOKING_SERVICE_DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${BOOKING_SERVICE_DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${BOOKING_SERVICE_DATABASE_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${BOOKING_SERVICE_KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${BOOKING_SERVICE_KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM_NAME: ${KEYCLOAK_REALM_NAME}
      KEYCLOAK_BASE_URI: ${KEYCLOAK_BASE_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
    env_file:
      - .env
    volumes:
      - ./booking-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
    restart: on-failure
    network_mode: "host"
