services:
  estate-service:
    container_name: estate-service
    image: estate-service
    build:
      context: estate-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    volumes:
      - ./estate-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.estate-service.rule=Host(`estate-service.domain.com`)"
      - "traefik.http.routers.estate-service.entrypoints=web"
    restart: on-failure
    network_mode: "host"

  static-service:
    container_name: static-service
    image: static-service
    build:
      context: static-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    volumes:
      - ./static-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
      - redis
    restart: on-failure
    network_mode: "host"

  user-service:
    container_name: user-service
    image: user-service
    build:
      context: user-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    volumes:
      - ./user-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
    restart: on-failure
    network_mode: "host"


  #  client-ui-service:
  #    container_name: client-ui-service
  #    build:
  #      context: ./client-ui-service
  #      dockerfile: Dockerfile
  #    volumes:
  #      - ./client-ui-service:/app
  #    depends_on:
  #      - keycloak
  #    network_mode: "host"

#  client-ui-react:
#    container_name: client-ui-react
#    build:
#      context: ./client-ui-react
#      dockerfile: Dockerfile
#    volumes:
#      - ./client-ui-react:/app
#    depends_on:
#      - keycloak
#    network_mode: "host"

#  admin-ui-service:
#    container_name: admin-ui-service
#    build:
#      context: ./admin-ui-service
#      dockerfile: Dockerfile
#    volumes:
#      - ./admin-ui-service:/app
#    depends_on:
#      - keycloak
#    network_mode: "host"