version: "3"

services:
  consul:
    container_name: consul
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
    command:
      - agent
      - -dev
      - -client=0.0.0.0
      - -log-level=ERR
    networks:
      - swann_network
    logging:
      driver: none

  traefik:
    container_name: traefik
    image: traefik:v3.0
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --api.insecure=true
      - --providers.consulcatalog
      - --providers.consulcatalog.endpoint.address=http://consul:8500
      - --providers.consulcatalog.prefix=traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.krakend.rule=Host(`api-gateway.local`)"
      - "traefik.http.routers.krakend.entrypoints=web"
    ports:
      - "8000:80"
      - "9090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
    networks:
      - swann_network

  krakend:
    container_name: krakend
    image: devopsfaith/krakend:latest
    ports:
      - "8888:8080"
#    volumes:
#      - ./krakend/krakend.json:/etc/krakend/krakend.json
    environment:
      - DEBUG=1
    networks:
      - swann_network

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    network_mode: "host"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    network_mode: "host"

  redis:
    container_name: redis
    image: redis
#    volumes:
#      - redis-data:/data
    network_mode: "host"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://localhost:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm" ]
    depends_on:
      - mysql
    network_mode: "host"

  static-service:
    container_name: static-service
    image: static-service
    build:
      context: static-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    volumes:
      - ./static-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
      - redis
    restart: on-failure
    network_mode: "host"

  estate-service:
    container_name: estate-service
    image: estate-service
    build:
      context: estate-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
    volumes:
      - ./estate-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - postgres
      - keycloak
    restart: on-failure
    network_mode: "host"

  client-ui-service:
    container_name: client-ui-service
    build:
      context: ./client-ui-service
      dockerfile: Dockerfile
    volumes:
      - ./client-ui-service:/app
    depends_on:
      - keycloak
    network_mode: "host"

  admin-ui-service:
    container_name: admin-ui-service
    build:
      context: ./admin-ui-service
      dockerfile: Dockerfile
    volumes:
      - ./admin-ui-service:/app
    depends_on:
      - keycloak
    network_mode: "host"

networks:
  swann_network: