export enum AUTH {
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",

    // REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST",
    // REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS",
    // REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE",

    REGISTER_REQUEST = "REGISTER_REQUEST",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",
    REGISTER_FAILURE = "REGISTER_FAILURE",

    LOGOUT_REQUEST = "LOGOUT_REQUEST",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
    LOGOUT_FAILURE = "LOGOUT_FAILURE",

    REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST",
    REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS",
    REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE",

    COOKIE_ACCEPTED = "COOKIE_ACCEPTED",
}

export enum PROPERTY {
    GET_HOME_PAGE_PROPERTIES_REQUEST = "GET_HOME_PAGE_PROPERTIES_REQUEST",
    GET_HOME_PAGE_PROPERTIES_SUCCESS = "GET_HOME_PAGE_PROPERTIES_SUCCESS",
    GET_HOME_PAGE_PROPERTIES_FAILURE = "GET_HOME_PAGE_PROPERTIES_FAILURE",

    GET_HOME_PAGE_FEATURED_PROPERTIES_REQUEST = "GET_HOME_PAGE_FEATURED_PROPERTIES_REQUEST",
    GET_HOME_PAGE_FEATURED_PROPERTIES_SUCCESS = "GET_HOME_PAGE_FEATURED_PROPERTIES_SUCCESS",
    GET_HOME_PAGE_FEATURED_PROPERTIES_FAILURE = "GET_HOME_PAGE_FEATURED_PROPERTIES_FAILURE",

    ADD_PROPERTY_REQUEST = 'ADD_PROPERTY_REQUEST',
    ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS',
    ADD_PROPERTY_FAILURE = 'ADD_PROPERTY_FAILURE',
    ADD_PROPERTY_SUCCESSFUL = 'ADD_PROPERTY_SUCCESSFUL',

    GET_PROPERTIES_REQUEST = 'GET_PROPERTIES_REQUEST',
    GET_PROPERTIES_SUCCESS = 'GET_PROPERTIES_SUCCESS',
    GET_PROPERTIES_FAILURE = 'GET_PROPERTIES_FAILURE',

    SEARCH_PROPERTIES_REQUEST = 'SEARCH_PROPERTIES_REQUEST',
    SEARCH_PROPERTIES_SUCCESS = 'SEARCH_PROPERTIES_SUCCESS',
    SEARCH_PROPERTIES_FAILURE = 'SEARCH_PROPERTIES_FAILURE',

    GET_PROPERTIES_BY_USER_REQUEST = 'GET_PROPERTIES_BY_USER_REQUEST',
    GET_PROPERTIES_BY_USER_SUCCESS = 'GET_PROPERTIES_BY_USER_SUCCESS',
    GET_PROPERTIES_BY_USER_FAILURE = 'GET_PROPERTIES_BY_USER_FAILURE',
    GET_PROPERTIES_BY_USER_CLEAN = 'GET_PROPERTIES_BY_USER_CLEAN',

    EDIT_PROPERTY_REQUEST = 'EDIT_PROPERTY_REQUEST',
    EDIT_PROPERTY_SUCCESS = 'EDIT_PROPERTY_SUCCESS',
    EDIT_PROPERTY_FAILURE = 'EDIT_PROPERTY_FAILURE',

    GET_WISH_LIST_PROPERTIES_REQUEST = 'GET_WISH_LIST_PROPERTIES_REQUEST',
    GET_WISH_LIST_PROPERTIES_SUCCESS = 'GET_WISH_LIST_PROPERTIES_SUCCESS',
    GET_WISH_LIST_PROPERTIES_FAILURE = 'GET_WISH_LIST_PROPERTIES_FAILURE',

    GET_WISH_LIST_PROPERTIES_BY_USER_REQUEST = 'GET_WISH_LIST_PROPERTIES_BY_USER_REQUEST',
    GET_WISH_LIST_PROPERTIES_BY_USER_SUCCESS = 'GET_WISH_LIST_PROPERTIES_BY_USER_SUCCESS',
    GET_WISH_LIST_PROPERTIES_BY_USER_FAILURE = 'GET_WISH_LIST_PROPERTIES_BY_USER_FAILURE',

    ADD_WISH_LIST_PROPERTY_BY_USER_REQUEST = 'ADD_WISH_LIST_PROPERTY_BY_USER_REQUEST',
    ADD_WISH_LIST_PROPERTY_BY_USER_SUCCESS = 'ADD_WISH_LIST_PROPERTY_BY_USER_SUCCESS',
    ADD_WISH_LIST_PROPERTY_BY_USER_FAILURE = 'ADD_WISH_LIST_PROPERTY_BY_USER_FAILURE',

    DELETE_WISH_LIST_PROPERTY_BY_USER_REQUEST = 'DELETE_WISH_LIST_PROPERTY_BY_USER_REQUEST',
    DELETE_WISH_LIST_PROPERTY_BY_USER_SUCCESS = 'DELETE_WISH_LIST_PROPERTY_BY_USER_SUCCESS',
    DELETE_WISH_LIST_PROPERTY_BY_USER_FAILURE = 'DELETE_WISH_LIST_PROPERTY_BY_USER_FAILURE',

    INSERT_PROPERTY_ELEMENT = 'INSERT_PROPERTY_ELEMENT',
    REMOVE_PROPERTY_ELEMENT = 'REMOVE_PROPERTY_ELEMENT',

    INSERT_EDIT_PROPERTY_ELEMENT = 'INSERT_EDIT_PROPERTY_ELEMENT'
}

export enum BLOG {
    INSERT_BLOG_ELEMENT = 'INSERT_BLOG_ELEMENT',
    REMOVE_BLOG_ELEMENT = 'REMOVE_BLOG_ELEMENT',
    REMOVE_ADD_BLOG_ERROR = 'REMOVE_ADD_BLOG_ERROR',

    GET_BLOG_REQUEST = 'GET_BLOG_REQUEST',
    GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS',
    GET_BLOG_FAILURE = 'GET_BLOG_FAILURE',
    GET_BLOG_CLEAN = 'GET_BLOG_CLEAN',

    GET_BLOG_BY_USERNAME_REQUEST = 'GET_BLOG_BY_USERNAME_REQUEST',
    GET_BLOG_BY_USERNAME_SUCCESS = 'GET_BLOG_BY_USERNAME_SUCCESS',
    GET_BLOG_BY_USERNAME_FAILURE = 'GET_BLOG_BY_USERNAME_FAILURE',

    ADD_BLOG_REQUEST = 'ADD_BLOG_REQUEST',
    ADD_BLOG_SUCCESS = 'ADD_BLOG_SUCCESS',
    ADD_BLOG_FAILURE = 'ADD_BLOG_FAILURE',

    GET_ADS_BLOG_REQUEST = 'GET_ADS_BLOG_REQUEST',
    GET_ADS_BLOG_SUCCESS = 'GET_ADS_BLOG_SUCCESS',
    GET_ADS_BLOG_FAILURE = 'GET_ADS_BLOG_FAILURE',

    GET_HOMEPAGE_BLOG_REQUEST = 'GET_HOMEPAGE_BLOG_REQUEST',
    GET_HOMEPAGE_BLOG_SUCCESS = 'GET_HOMEPAGE_BLOG_SUCCESS',
    GET_HOMEPAGE_BLOG_FAILURE = 'GET_HOMEPAGE_BLOG_FAILURE',
}

export enum USER {
    GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST',
    GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS',
    GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE',
}

export enum STATIC {
    GET_STATIC_REQUEST = 'GET_STATIC_REQUEST',
    GET_STATIC_SUCCESS = 'GET_STATIC_SUCCESS',
    GET_STATIC_FAILURE = 'GET_STATIC_FAILURE',

    GET_STATIC_CATEGORY_DATA_REQUEST = 'GET_STATIC_CATEGORY_DATA_REQUEST',
    GET_STATIC_CATEGORY_DATA_SUCCESS = 'GET_STATIC_CATEGORY_DATA_SUCCESS',
    GET_STATIC_CATEGORY_DATA_FAILURE = 'GET_STATIC_CATEGORY_DATA_FAILURE',

    GET_PRICE_PACKAGES_REQUEST = 'GET_PRICE_PACKAGES_REQUEST',
    GET_PRICE_PACKAGES_SUCCESS = 'GET_PRICE_PACKAGES_SUCCESS',
    GET_PRICE_PACKAGES_FAILURE = 'GET_PRICE_PACKAGES_FAILURE',

    GET_COOKIE_POLICY_REQUEST = 'GET_COOKIE_POLICY_REQUEST',
    GET_COOKIE_POLICY_SUCCESS = 'GET_COOKIE_POLICY_SUCCESS',
    GET_COOKIE_POLICY_FAILURE = 'GET_COOKIE_POLICY_FAILURE',
}

export enum NOTICES {
    GET_ALL_NOTICES_REQUEST = 'GET_ALL_NOTICES_REQUEST',
    GET_ALL_NOTICES_SUCCESS = 'GET_ALL_NOTICES_SUCCESS',
    GET_ALL_NOTICES_FAILURE = 'GET_ALL_NOTICES_FAILURE',
}

export enum EMAIL_TYPES {
    REQUEST_SEARCH_ALERT = 'REQUEST_SEARCH_ALERT',
    SUCCESS_SEARCH_ALERT = 'SUCCESS_SEARCH_ALERT',
    FAILURE_SEARCH_ALERT = 'FAILURE_SEARCH_ALERT',
}

export enum SEARCH_ALERT_TYPES {
    GET_SEARCH_ALERTS_REQUEST = 'GET_SEARCH_ALERTS_REQUEST',
    GET_SEARCH_ALERTS_SUCCESS = 'GET_SEARCH_ALERTS_SUCCESS',
    GET_SEARCH_ALERTS_FAILURE = 'GET_SEARCH_ALERTS_FAILURE',

    GET_SEARCH_ALERT_AUTH_REQUEST = 'GET_SEARCH_ALERT_AUTH_REQUEST',
    GET_SEARCH_ALERT_AUTH_SUCCESS = 'GET_SEARCH_ALERT_AUTH_SUCCESS',
    GET_SEARCH_ALERT_AUTH_FAILURE = 'GET_SEARCH_ALERT_AUTH_FAILURE',

    ADD_SEARCH_ALERT_REQUEST = 'ADD_SEARCH_ALERT_REQUEST',
    ADD_SEARCH_ALERT_SUCCESS = 'ADD_SEARCH_ALERT_SUCCESS',
    ADD_SEARCH_ALERT_FAILURE = 'ADD_SEARCH_ALERT_FAILURE',

    DELETE_SEARCH_ALERT_REQUEST = 'DELETE_SEARCH_ALERT_REQUEST',
    DELETE_SEARCH_ALERT_SUCCESS = 'DELETE_SEARCH_ALERT_SUCCESS',
    DELETE_SEARCH_ALERT_FAILURE = 'DELETE_SEARCH_ALERT_FAILURE',

    UPDATE_SEARCH_ALERT_REQUEST = 'UPDATE_SEARCH_ALERT_REQUEST',
    UPDATE_SEARCH_ALERT_SUCCESS = 'UPDATE_SEARCH_ALERT_SUCCESS',
    UPDATE_SEARCH_ALERT_FAILURE = 'UPDATE_SEARCH_ALERT_FAILURE',

    GET_SEARCH_ALERTS_BY_USER_REQUEST = 'GET_SEARCH_ALERTS_BY_USER_REQUEST',
    GET_SEARCH_ALERTS_BY_USER_SUCCESS = 'GET_SEARCH_ALERTS_BY_USER_SUCCESS',
    GET_SEARCH_ALERTS_BY_USER_FAILURE = 'GET_SEARCH_ALERTS_BY_USER_FAILURE',

    ADD_SEARCH_ALERT_BY_USER_REQUEST = 'ADD_SEARCH_ALERT_BY_USER_REQUEST',
    ADD_SEARCH_ALERT_BY_USER_SUCCESS = 'ADD_SEARCH_ALERT_BY_USER_SUCCESS',
    ADD_SEARCH_ALERT_BY_USER_FAILURE = 'ADD_SEARCH_ALERT_BY_USER_FAILURE',

    DELETE_SEARCH_ALERT_BY_USER_REQUEST = 'DELETE_SEARCH_ALERT_BY_USER_REQUEST',
    DELETE_SEARCH_ALERT_BY_USER_SUCCESS = 'DELETE_SEARCH_ALERT_BY_USER_SUCCESS',
    DELETE_SEARCH_ALERT_BY_USER_FAILURE = 'DELETE_SEARCH_ALERT_BY_USER_FAILURE',

    UPDATE_SEARCH_ALERT_BY_USER_REQUEST = 'UPDATE_SEARCH_ALERT_BY_USER_REQUEST',
    UPDATE_SEARCH_ALERT_BY_USER_SUCCESS = 'UPDATE_SEARCH_ALERT_BY_USER_SUCCESS',
    UPDATE_SEARCH_ALERT_BY_USER_FAILURE = 'UPDATE_SEARCH_ALERT_BY_USER_FAILURE',

    VALIDATE_SEARCH_ALERT_REQUEST = 'VALIDATE_SEARCH_ALERT_REQUEST',
    VALIDATE_SEARCH_ALERT_SUCCESS = 'VALIDATE_SEARCH_ALERT_SUCCESS',
    VALIDATE_SEARCH_ALERT_FAILURE = 'VALIDATE_SEARCH_ALERT_FAILURE',

    VALIDATE_SEARCH_ALERT_BY_USER_REQUEST = 'VALIDATE_SEARCH_ALERT_BY_USER_REQUEST',
    VALIDATE_SEARCH_ALERT_BY_USER_SUCCESS = 'VALIDATE_SEARCH_ALERT_BY_USER_SUCCESS',
    VALIDATE_SEARCH_ALERT_BY_USER_FAILURE = 'VALIDATE_SEARCH_ALERT_BY_USER_FAILURE',
}

export enum SETTINGS_TYPES {
    GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST',
    GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS',
    GET_SETTINGS_FAILURE = 'GET_SETTINGS_FAILURE',
}

export enum LANGUAGE_TYPES {
    SET_LANGUAGE = 'SET_LANGUAGE',
}