spring:
  application:
    name: estate-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/estate-service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/estate-service}
    user: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    drop-first: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fortunatishomes
server:
  port: ${SPRING_APPLICATION_PORT:8182}

service:
  param:
    keycloak-service:
      token-url: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/fortunatishomes}/protocol/openid-connect/token
      client-id: ${KEYCLOAK_CLIENT_ID:estate-api}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:**********}
    static-service:
      base-url: ${STATIC_SERVICE_URL:http://localhost:8181}
      public-prefix: /public
      endpoint-prefix: /api/v1
    user-service:
      base-url: ${USER_SERVICE_URL:http://localhost:8183}
    email-service:
      base-url: ${EMAIL_SERVICE_URL:http://localhost:8184}
      endpoint-prefix: /api/v1
    file-storage:
      dir: https://fotunatishome.s3.amazonaws.com/
      users-dir: fortunatis-real-estate/uploads/users/
      admin-dir: fortunatis-real-estate/uploads/admin/
cloud:
  aws:
    s3:
      bucket: fotunatishome
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA6BSS4IPSO3FL5LDX
      secretKey: 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

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI


logging:
  level:
    root: INFO
springdoc:
  show-actuator: false
  enable-kotlin: false
  swagger-ui:
    doc-expansion: none
