spring:
  application:
    name: estate-service
  config:
    import: "optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 5s
      config:
        enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/estate-service
    username: root
    password: root
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fortunatishomes
server:
  port: 8182

service:
  param:
    static-service:
      base-url: http://localhost:8181
      enpoint-prefix: ${service.param.static-service.base-url}/public/api/v1/static

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI


logging:
  level:
    root: INFO
springdoc:
  show-actuator: false
  enable-kotlin: false
  swagger-ui:
    doc-expansion: none
