spring:
  application:
    name: static-data-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/estate-service
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fortunatishomes
server:
  port: 8182

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI


logging:
  level:
    root: INFO
springdoc:
  show-actuator: true
