spring:
  application:
    name: static-data-service
  config:
    import: "optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/"
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 5s
      config:
        enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/static-data-service
    username: root
    password: root
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    url: jdbc:postgresql://localhost:5432/static-data-service
    user: root
    password: root
    drop-first: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/fortunatishomes
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8181

service:
  param:
    keycloak:
      base-url: http://localhost:8181

      client-id: static-service

      grant-type: client_credentials
    user-service:
      base-url: http://localhost:8183/v1

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI

logging:
  level:
    root: INFO
springdoc:
  show-actuator: true
  enable-kotlin: false
  swagger-ui:
    doc-expansion: none