spring:
  application:
    name: static-data-service
  datasource:
    url: jdbc:postgresql://postgres:5432/static-data-service
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    url: jdbc:postgresql://postgres:5432/static-data-service
    user: root
    password: root
    drop-first: false
server:
  port: 8181

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI

logging:
  level:
    root: INFO