server:
  port: 8183
spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: root
    password: root
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    url: jdbc:postgresql://localhost:5432/user-service
    user: root
    password: root
    drop-first: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fortunatishomes
service:
  param:
    keycloak:
      base-url: http://localhost:8181
      realm: fortunatishomes
      client-id: static-service
      client-secret: XuCIzeFc43F3NqBYqpaAYoab7NBD08et
      grant-type: client_credentials

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI
stripe:
  key:
    secret: sk_test_51MLhApA4Ym4lDK6RzszOPSgfGlecEa0FMLOKGqpx1viirNSdRlf7lp0LaPGmhR1kuY3oxBEc8n6UFxw0xjgWbFqr00e6Yxo35v

logging:
  level:
    root: INFO
springdoc:
  show-actuator: true
  enable-kotlin: false
  swagger-ui:
    doc-expansion: none
