server:
  port: ${SPRING_APPLICATION_PORT:8183}
spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/user-service}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    url: ${SPRING_DATABASE_URL:jdbc:postgresql://localhost:5432/user-service}
    user: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    drop-first: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/fortunatishomes}
service:
  param:
    keycloak:
      base-url: ${KEYCLOAK_BASE_URI:http://localhost:8181}
      realm: ${KEYCLOAK_REALM_NAME:fortunatishomes}
      client-id: ${KEYCLOAK_CLIENT_ID:user-api}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:**********}
      grant-type: client_credentials

springfox:
  documentation:
    type: swagger_2
    enabled: true  # Set false to disable
  swagger-ui:
    base-url: /swagger-ui/  # URL to access swagger UI
stripe:
  key:
    secret: sk_test_51MLhApA4Ym4lDK6RzszOPSgfGlecEa0FMLOKGqpx1viirNSdRlf7lp0LaPGmhR1kuY3oxBEc8n6UFxw0xjgWbFqr00e6Yxo35v

logging:
  level:
    root: INFO
springdoc:
  show-actuator: true
  enable-kotlin: false
  swagger-ui:
    doc-expansion: none
