worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8000;
        server_name estate-service.domain.com;

        location /static-api {
            rewrite ^/static-api(.*)$ $1 break;
            proxy_pass http://localhost:8181;  # Adjust the port if needed
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Script-Name /static-api;
            proxy_set_header X-Forwarded-Uri /static-api;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
        }

        location /estate-api {
            rewrite ^/estate-api(.*)$ $1 break;
            proxy_pass http://localhost:8182;  # Adjust the port if needed
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Script-Name /estate-api;
            proxy_set_header X-Forwarded-Uri /estate-api;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
        }

        location /user-api {
            rewrite ^/user-api(.*)$ $1 break;
            proxy_pass http://localhost:8183;  # Adjust the port if needed
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Script-Name /user-api;
            proxy_set_header X-Forwarded-Uri /user-api;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
        }
    }
}
