INSERT INTO public.countrys (alpha_2, country_code, country_name, is_active, region, sub_region)
VALUES ('AF', '004', 'Afghanistan', false, 'Asia', 'Southern Asia'),
       ('AX', '248', 'Åland Islands', false, 'Europe', 'Northern Europe'),
       ('AL', '008', 'Albania', false, 'Europe', 'Southern Europe'),
       ('DZ', '012', 'Algeria', false, 'Africa', 'Northern Africa'),
       ('BD', '050', 'Bangladesh', true, 'Asia', 'Southern Asia'),
       ('BG', '100', 'Bulgaria', true, 'Europe', 'Eastern Europe'),
       ('IS', '352', 'Iceland', false, 'Europe', 'Northern Europe'),
       ('KP', '408', 'Korea (Democratic People''s Republic of)', false, 'Asia', 'Eastern Asia'),
       ('VE', '862', 'Venezuela (Bolivarian Republic of)', false, 'Americas', 'Latin America and the Caribbean'),
       ('VN', '704', 'Viet Nam', false, 'Asia', 'South-eastern Asia'),
       ('VG', '092', 'Virgin Islands (British)', true, 'Americas', 'Latin America and the Caribbean, '),
       ('VI', '850', 'Virgin Islands (U.S.)', true, 'Americas', 'Latin America and the Caribbean, '),
       ('YE', '887', 'Yemen', true, 'Asia', 'Western Asia, '),
       ('AS', '16', 'American Samoa', true, 'Oceania', 'Polynesia, '),
       ('AD', '20', 'Andorra', true, 'Europe', 'Southern Europe, '),
       ('AO', '24', 'Angola', true, 'Africa', 'Sub-Saharan Africa, '),
       ('AI', '660', 'Anguilla', true, 'Americas', 'Latin America and the Caribbean, '),
       ('AG', '28', 'Antigua and Barbuda', true, 'Americas', 'Latin America and the Caribbean, '),
       ('AM', '51', 'Armenia', true, 'Asia', 'Western Asia, '),
       ('AW', '533', 'Aruba', true, 'Americas', 'Latin America and the Caribbean, '),
       ('AZ', '31', 'Azerbaijan', true, 'Asia', 'Western Asia, '),
       ('BS', '44', 'Bahamas', true, 'Americas', 'Latin America and the Caribbean, '),
       ('BH', '48', 'Bahrain', true, 'Asia', 'Western Asia, '),
       ('BB', '52', 'Barbados', true, 'Americas', 'Latin America and the Caribbean, '),
       ('BY', '112', 'Belarus', true, 'Europe', 'Eastern Europe, '),
       ('BZ', '84', 'Belize', true, 'Americas', 'Latin America and the Caribbean, '),
       ('BM', '60', 'Bermuda', true, 'Americas', 'Northern America, '),
       ('BJ', '204', 'Benin', true, 'Africa', 'Sub-Saharan Africa, '),
       ('BT', '64', 'Bhutan', true, 'Asia', 'Southern Asia, '),
       ('BO', '68', 'Bolivia', true, 'Americas', 'Latin America and the Caribbean, '),
       ('BQ', '535', 'Bonaire, Sint Eustatius and Saba', true, 'Americas', 'Latin America and the Caribbean, '),
       ('BA', '70', 'Bosnia and Herzegovina', true, 'Europe', 'Southern Europe, '),
       ('BW', '72', 'Botswana', true, 'Africa', 'Sub-Saharan Africa, '),
       ('BV', '74', 'Bouvet Island', true, 'Americas', 'Latin America and the Caribbean, '),
       ('IO', '86', 'British Indian Ocean Territory', true, 'Africa', 'Sub-Saharan Africa, '),
       ('BN', '96', 'Brunei Darussalam', true, 'Asia', 'South-eastern Asia, '),
       ('BF', '854', 'Burkina Faso', true, 'Africa', 'Sub-Saharan Africa, '),
       ('BI', '108', 'Burundi', true, 'Africa', 'Sub-Saharan Africa, '),
       ('CV', '132', 'Cabo Verde', true, 'Africa', 'Sub-Saharan Africa, '),
       ('KH', '116', 'Cambodia', true, 'Asia', 'South-eastern Asia, '),
       ('CM', '120', 'Cameroon', true, 'Africa', 'Sub-Saharan Africa, '),
       ('KY', '136', 'Cayman Islands', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CF', '140', 'Central African Republic', true, 'Africa', 'Sub-Saharan Africa, '),
       ('TD', '148', 'Chad', true, 'Africa', 'Sub-Saharan Africa, '),
       ('CX', '162', 'Christmas Island', true, 'Oceania', 'Australia and New Zealand, '),
       ('CC', '166', 'Cocos (Keeling) Islands', true, 'Oceania', 'Australia and New Zealand, '),
       ('KM', '174', 'Comoros', true, 'Africa', 'Sub-Saharan Africa, '),
       ('CG', '178', 'Congo', true, 'Africa', 'Sub-Saharan Africa, '),
       ('CD', '180', 'Congo (Democratic Republic of the)', true, 'Africa', 'Sub-Saharan Africa, '),
       ('CK', '184', 'Cook Islands', true, 'Oceania', 'Polynesia, '),
       ('CR', '188', 'Costa Rica', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CI', '384', 'Côte d''Ivoire', true, 'Africa', 'Sub-Saharan Africa, '),
       ('HR', '191', 'Croatia', true, 'Europe', 'Southern Europe, '),
       ('CU', '192', 'Cuba', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CW', '531', 'Curaçao', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CY', '196', 'Cyprus', true, 'Asia', 'Western Asia, '),
       ('DJ', '262', 'Djibouti', true, 'Africa', 'Sub-Saharan Africa, '),
       ('DM', '212', 'Dominica', true, 'Americas', 'Latin America and the Caribbean, '),
       ('DO', '214', 'Dominican Republic', true, 'Americas', 'Latin America and the Caribbean, '),
       ('EC', '218', 'Ecuador', true, 'Americas', 'Latin America and the Caribbean, '),
       ('SV', '222', 'El Salvador', true, 'Americas', 'Latin America and the Caribbean, '),
       ('GQ', '226', 'Equatorial Guinea', true, 'Africa', 'Sub-Saharan Africa, '),
       ('ER', '232', 'Eritrea', true, 'Africa', 'Sub-Saharan Africa, '),
       ('EE', '233', 'Estonia', true, 'Europe', 'Northern Europe, '),
       ('SZ', '748', 'Eswatini', true, 'Africa', 'Sub-Saharan Africa, '),
       ('ET', '231', 'Ethiopia', true, 'Africa', 'Sub-Saharan Africa, '),
       ('FK', '238', 'Falkland Islands (Malvinas)', true, 'Americas', 'Latin America and the Caribbean, '),
       ('FO', '234', 'Faroe Islands', true, 'Europe', 'Northern Europe, '),
       ('FJ', '242', 'Fiji', true, 'Oceania', 'Melanesia, '),
       ('GF', '254', 'French Guiana', true, 'Americas', 'Latin America and the Caribbean, '),
       ('PF', '258', 'French Polynesia', true, 'Oceania', 'Polynesia, '),
       ('TF', '260', 'French Southern Territories', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GA', '266', 'Gabon', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GM', '270', 'Gambia', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GE', '268', 'Georgia', true, 'Asia', 'Western Asia, '),
       ('GH', '288', 'Ghana', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GI', '292', 'Gibraltar', true, 'Europe', 'Southern Europe, '),
       ('GL', '304', 'Greenland', true, 'Americas', 'Northern America, '),
       ('GD', '308', 'Grenada', true, 'Americas', 'Latin America and the Caribbean, '),
       ('GP', '312', 'Guadeloupe', true, 'Americas', 'Latin America and the Caribbean, '),
       ('GU', '316', 'Guam', true, 'Oceania', 'Micronesia, '),
       ('GT', '320', 'Guatemala', true, 'Americas', 'Latin America and the Caribbean, '),
       ('GG', '831', 'Guernsey', true, 'Europe', 'Northern Europe, '),
       ('GN', '324', 'Guinea', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GW', '624', 'Guinea-Bissau', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GY', '328', 'Guyana', true, 'Americas', 'Latin America and the Caribbean, '),
       ('HT', '332', 'Haiti', true, 'Americas', 'Latin America and the Caribbean, '),
       ('HM', '334', 'Heard Island and McDonald Islands', true, 'Oceania', 'Australia and New Zealand, '),
       ('VA', '336', 'Holy See', true, 'Europe', 'Southern Europe, '),
       ('HN', '340', 'Honduras', true, 'Americas', 'Latin America and the Caribbean, '),
       ('IR', '364', 'Iran (Islamic Republic of)', true, 'Asia', 'Southern Asia, '),
       ('IQ', '368', 'Iraq', true, 'Asia', 'Western Asia, '),
       ('IM', '833', 'Isle of Man', true, 'Europe', 'Northern Europe, '),
       ('IL', '376', 'Israel', true, 'Asia', 'Western Asia, '),
       ('JM', '388', 'Jamaica', true, 'Americas', 'Latin America and the Caribbean, '),
       ('JE', '832', 'Jersey', true, 'Europe', 'Northern Europe, '),
       ('JO', '400', 'Jordan', true, 'Asia', 'Western Asia, '),
       ('KZ', '398', 'Kazakhstan', true, 'Asia', 'Central Asia, '),
       ('KE', '404', 'Kenya', true, 'Africa', 'Sub-Saharan Africa, '),
       ('KI', '296', 'Kiribati', true, 'Oceania', 'Micronesia, '),
       ('KW', '414', 'Kuwait', true, 'Asia', 'Western Asia, '),
       ('KG', '417', 'Kyrgyzstan', true, 'Asia', 'Central Asia, '),
       ('LA', '418', 'Lao People''s Democratic Republic', true, 'Asia', 'South-eastern Asia, '),
       ('LV', '428', 'Latvia', true, 'Europe', 'Northern Europe, '),
       ('LB', '422', 'Lebanon', true, 'Asia', 'Western Asia, '),
       ('LS', '426', 'Lesotho', true, 'Africa', 'Sub-Saharan Africa, '),
       ('LR', '430', 'Liberia', true, 'Africa', 'Sub-Saharan Africa, '),
       ('LY', '434', 'Libya', true, 'Africa', 'Northern Africa, '),
       ('LI', '438', 'Liechtenstein', true, 'Europe', 'Western Europe, '),
       ('LT', '440', 'Lithuania', true, 'Europe', 'Northern Europe, '),
       ('LU', '442', 'Luxembourg', true, 'Europe', 'Western Europe, '),
       ('MO', '446', 'Macao', true, 'Asia', 'Eastern Asia, '),
       ('MK', '807', 'Macedonia', true, 'Europe', 'Southern Europe, '),
       ('MG', '450', 'Madagascar', true, 'Africa', 'Sub-Saharan Africa, '),
       ('MW', '454', 'Malawi', true, 'Africa', 'Sub-Saharan Africa, '),
       ('MV', '462', 'Maldives', true, 'Asia', 'Southern Asia, '),
       ('ML', '466', 'Mali', true, 'Africa', 'Sub-Saharan Africa, '),
       ('MT', '470', 'Malta', true, 'Europe', 'Southern Europe, '),
       ('MH', '584', 'Marshall Islands', true, 'Oceania', 'Micronesia, '),
       ('MQ', '474', 'Martinique', true, 'Americas', 'Latin America and the Caribbean, '),
       ('MR', '478', 'Mauritania', true, 'Africa', 'Sub-Saharan Africa, '),
       ('MU', '480', 'Mauritius', true, 'Africa', 'Sub-Saharan Africa, '),
       ('YT', '175', 'Mayotte', true, 'Africa', 'Sub-Saharan Africa, '),
       ('FM', '583', 'Micronesia (Federated States of)', true, 'Oceania', 'Micronesia, '),
       ('MD', '498', 'Moldova (Republic of)', true, 'Europe', 'Eastern Europe, '),
       ('MC', '492', 'Monaco', true, 'Europe', 'Western Europe, '),
       ('MN', '496', 'Mongolia', true, 'Asia', 'Eastern Asia, '),
       ('ME', '499', 'Montenegro', true, 'Europe', 'Southern Europe, '),
       ('MS', '500', 'Montserrat', true, 'Americas', 'Latin America and the Caribbean, '),
       ('MA', '504', 'Morocco', true, 'Africa', 'Northern Africa, '),
       ('MZ', '508', 'Mozambique', true, 'Africa', 'Sub-Saharan Africa, '),
       ('MM', '104', 'Myanmar', true, 'Asia', 'South-eastern Asia, '),
       ('NA', '516', 'Namibia', true, 'Africa', 'Sub-Saharan Africa, '),
       ('NR', '520', 'Nauru', true, 'Oceania', 'Micronesia, '),
       ('NP', '524', 'Nepal', true, 'Asia', 'Southern Asia, '),
       ('NC', '540', 'New Caledonia', true, 'Oceania', 'Melanesia, '),
       ('NI', '558', 'Nicaragua', true, 'Americas', 'Latin America and the Caribbean, '),
       ('NE', '562', 'Niger', true, 'Africa', 'Sub-Saharan Africa, '),
       ('NG', '566', 'Nigeria', true, 'Africa', 'Sub-Saharan Africa, '),
       ('NU', '570', 'Niue', true, 'Oceania', 'Polynesia, '),
       ('NF', '574', 'Norfolk Island', true, 'Oceania', 'Australia and New Zealand, '),
       ('MP', '580', 'Northern Mariana Islands', true, 'Oceania', 'Micronesia, '),
       ('OM', '512', 'Oman', true, 'Asia', 'Western Asia, '),
       ('PW', '585', 'Palau', true, 'Oceania', 'Micronesia, '),
       ('PS', '275', 'Palestine, State of', true, 'Asia', 'Western Asia, '),
       ('PA', '591', 'Panama', true, 'Americas', 'Latin America and the Caribbean, '),
       ('PG', '598', 'Papua New Guinea', true, 'Oceania', 'Melanesia, '),
       ('PY', '600', 'Paraguay', true, 'Americas', 'Latin America and the Caribbean, '),
       ('PN', '612', 'Pitcairn', true, 'Oceania', 'Polynesia, '),
       ('PR', '630', 'Puerto Rico', true, 'Americas', 'Latin America and the Caribbean, '),
       ('RE', '638', 'Réunion', true, 'Africa', 'Sub-Saharan Africa, '),
       ('RO', '642', 'Romania', true, 'Europe', 'Eastern Europe, '),
       ('RW', '646', 'Rwanda', true, 'Africa', 'Sub-Saharan Africa, '),
       ('BL', '652', 'Saint Barthélemy', true, 'Americas', 'Latin America and the Caribbean, '),
       ('SH', '654', 'Saint Helena, Ascension and Tristan da Cunha', true, 'Africa', 'Sub-Saharan Africa, '),
       ('KN', '659', 'Saint Kitts and Nevis', true, 'Americas', 'Latin America and the Caribbean, '),
       ('LC', '662', 'Saint Lucia', true, 'Americas', 'Latin America and the Caribbean, '),
       ('MF', '663', 'Saint Martin (French part)', true, 'Americas', 'Latin America and the Caribbean, '),
       ('PM', '666', 'Saint Pierre and Miquelon', true, 'Americas', 'Northern America, '),
       ('VC', '670', 'Saint Vincent and the Grenadines', true, 'Americas', 'Latin America and the Caribbean, '),
       ('WS', '882', 'Samoa', true, 'Oceania', 'Polynesia, '),
       ('SM', '674', 'San Marino', true, 'Europe', 'Southern Europe, '),
       ('ST', '678', 'Sao Tome and Principe', true, 'Africa', 'Sub-Saharan Africa, '),
       ('SN', '686', 'Senegal', true, 'Africa', 'Sub-Saharan Africa, '),
       ('RS', '688', 'Serbia', true, 'Europe', 'Southern Europe, '),
       ('SC', '690', 'Seychelles', true, 'Africa', 'Sub-Saharan Africa, '),
       ('SL', '694', 'Sierra Leone', true, 'Africa', 'Sub-Saharan Africa, '),
       ('SX', '534', 'Sint Maarten (Dutch part)', true, 'Americas', 'Latin America and the Caribbean, '),
       ('SK', '703', 'Slovakia', true, 'Europe', 'Eastern Europe, '),
       ('SI', '705', 'Slovenia', true, 'Europe', 'Southern Europe, '),
       ('SB', '90', 'Solomon Islands', true, 'Oceania', 'Melanesia, '),
       ('SO', '706', 'Somalia', true, 'Africa', 'Sub-Saharan Africa, '),
       ('GS', '239', 'South Georgia and the South Sandwich Islands', true, 'Americas',
        'Latin America and the Caribbean, '),
       ('SS', '728', 'South Sudan', true, 'Africa', 'Sub-Saharan Africa, '),
       ('LK', '144', 'Sri Lanka', true, 'Asia', 'Southern Asia, '),
       ('SD', '729', 'Sudan', true, 'Africa', 'Northern Africa, '),
       ('SR', '740', 'Suriname', true, 'Americas', 'Latin America and the Caribbean, '),
       ('SJ', '744', 'Svalbard and Jan Mayen', true, 'Europe', 'Northern Europe, '),
       ('SY', '760', 'Syrian Arab Republic', true, 'Asia', 'Western Asia, '),
       ('TJ', '762', 'Tajikistan', true, 'Asia', 'Central Asia, '),
       ('TZ', '834', 'Tanzania, United Republic of', true, 'Africa', 'Sub-Saharan Africa, '),
       ('TL', '626', 'Timor-Leste', true, 'Asia', 'South-eastern Asia, '),
       ('TG', '768', 'Togo', true, 'Africa', 'Sub-Saharan Africa, '),
       ('TK', '772', 'Tokelau', true, 'Oceania', 'Polynesia, '),
       ('TO', '776', 'Tonga', true, 'Oceania', 'Polynesia, '),
       ('TT', '780', 'Trinidad and Tobago', true, 'Americas', 'Latin America and the Caribbean, '),
       ('TN', '788', 'Tunisia', true, 'Africa', 'Northern Africa, '),
       ('TM', '795', 'Turkmenistan', true, 'Asia', 'Central Asia, '),
       ('TC', '796', 'Turks and Caicos Islands', true, 'Americas', 'Latin America and the Caribbean, '),
       ('TV', '798', 'Tuvalu', true, 'Oceania', 'Polynesia, '),
       ('UG', '800', 'Uganda', true, 'Africa', 'Sub-Saharan Africa'),
       ('UA', '804', 'Ukraine', true, 'Europe', 'Eastern Europe'),
       ('UM', '581', 'United States Minor Outlying Islands', true, 'Oceania', 'Micronesia'),
       ('UY', '858', 'Uruguay', true, 'Americas', 'Latin America and the Caribbean'),
       ('UZ', '860', 'Uzbekistan', false, 'Asia', 'Central Asia'),
       ('VU', '548', 'Vanuatu', true, 'Oceania', 'Melanesia'),
       ('WF', '876', 'Wallis and Futuna', false, 'Oceania', 'Polynesia'),
       ('EH', '732', 'Western Sahara', true, 'Africa', 'Northern Africa'),
       ('ZM', '894', 'Zambia', false, 'Africa', 'Sub-Saharan Africa'),
       ('ZW', '716', 'Zimbabwe', true, 'Africa', 'Sub-Saharan Africa'),
       ('EG', '818', 'Egypt', true, 'Africa', 'Northern Africa, '),
       ('GR', '300', 'Greece', true, 'Europe', 'Southern Europe, '),
       ('MY', '458', 'Malaysia', true, 'Asia', 'South-eastern Asia, '),
       ('MX', '484', 'Mexico', true, 'Americas', 'Latin America and the Caribbean, '),
       ('PL', '616', 'Poland', true, 'Europe', 'Eastern Europe, '),
       ('AE', '784', 'United Arab Emirates', true, 'Asia', 'Western Asia, '),
       ('IN', '356', 'India', true, 'Asia', 'Southern Asia, '),
       ('GB', '826', 'United Kingdom', true, 'Europe', 'Northern Europe, '),
       ('AR', '32', 'Argentina', true, 'Americas', 'Latin America and the Caribbean, '),
       ('BR', '76', 'Brazil', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CL', '152', 'Chile', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CO', '170', 'Colombia', true, 'Americas', 'Latin America and the Caribbean, '),
       ('CZ', '203', 'Czechia', true, 'Europe', 'Eastern Europe, '),
       ('HU', '348', 'Hungary', true, 'Europe', 'Eastern Europe, '),
       ('KR', '410', 'Korea (Republic of)', true, 'Asia', 'Eastern Asia, '),
       ('PK', '586', 'Pakistan', true, 'Asia', 'Southern Asia, '),
       ('PE', '604', 'Peru', true, 'Americas', 'Latin America and the Caribbean, '),
       ('PH', '608', 'Philippines', true, 'Asia', 'South-eastern Asia, '),
       ('QA', '634', 'Qatar', true, 'Asia', 'Western Asia, '),
       ('RU', '643', 'Russian Federation', true, 'Europe', 'Eastern Europe, '),
       ('SA', '682', 'Saudi Arabia', true, 'Asia', 'Western Asia, '),
       ('ZA', '710', 'South Africa', true, 'Africa', 'Sub-Saharan Africa, '),
       ('TW', '158', 'Taiwan, Province of China', true, 'Asia', 'Eastern Asia, '),
       ('TH', '764', 'Thailand', true, 'Asia', 'South-eastern Asia, '),
       ('TR', '792', 'Turkey', true, 'Asia', 'Western Asia, '),
       ('CN', '156', 'China', true, 'Asia', 'Eastern Asia, '),
       ('ID', '360', 'Indonesia', true, 'Asia', 'South-eastern Asia, '),
       ('JP', '392', 'Japan', true, 'Asia', 'Eastern Asia, '),
       ('US', '840', 'United States of America', true, 'Americas', 'Northern America, '),
       ('CA', '124', 'Canada', true, 'Americas', 'Northern America, '),
       ('CH', '756', 'Switzerland', true, 'Europe', 'Western Europe'),
       ('DK', '208', 'Denmark', false, 'Europe', 'Northern Europe'),
       ('FI', '246', 'Finland', true, 'Europe', 'Northern Europe'),
       ('FR', '250', 'France', true, 'Europe', 'Western Europe'),
       ('DE', '276', 'Germany', true, 'Europe', 'Western Europe'),
       ('IT', '380', 'Italy', true, 'Europe', 'Southern Europe'),
       ('NL', '528', 'Netherlands', true, 'Europe', 'Western Europe'),
       ('NO', '578', 'Norway', false, 'Europe', 'Northern Europe'),
       ('ES', '724', 'Spain', false, 'Europe', 'Southern Europe'),
       ('SE', '752', 'Sweden', true, 'Europe', 'Northern Europe'),
       ('AT', '40', 'Austria', true, 'Europe', 'Western Europe'),
       ('BE', '56', 'Belgium', true, 'Europe', 'Western Europe'),
       ('IE', '372', 'Ireland', true, 'Europe', 'Northern Europe'),
       ('PT', '620', 'Portugal', true, 'Europe', 'Southern Europe'),
       ('HK', '344', 'Hong Kong', false, 'Asia', 'Eastern Asia'),
       ('NZ', '554', 'New Zealand', true, 'Oceania', 'Australia and New Zealand'),
       ('SG', '702', 'Singapore', true, 'Asia', 'South-eastern Asia'),
       ('AU', '36', 'Australia', true, 'Oceania', 'Australia and New Zealand');
