apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: estate-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: estate-service.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: estate-service
                port:
                  number: 80
