apiVersion: v1
kind: Secret
metadata:
  name: estate-service-secrets
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded
  KEYCLOAK_CLIENT_SECRET: c2VjcmV0  # Base64 encoded
